FISTA_OPT = pnopt_optimset(...
        'debug'         , 0      ,... % debug mode 
        'desc_param'    , 0.0001 ,... % sufficient descent parameter
        'display'       , -10    ,... % display frequency (<= 0 for no display) 
        'backtrack_mem' , 10     ,... % number of previous function values to save
        'max_fun_evals' , 50000  ,... % max number of function evaluations
        'max_iter'      , 20   ,... % max number of iterations
        'ftol'          , 1e-4   ,... % stopping tolerance on objective function 
        'optim_tol'     , 1e-6   ,... % stopping tolerance on opt
        'xtol'          , 1e-9    ... % stopping tolerance on solution
        );

configurePara = struct(...
'inDataDir',  '../../../../AllData/multi_task/datas/',...
'resultDir',  '../../../../AllData/multi_task/results/',...    
'MTIL_L_Ln', struct(...
                   'inDataDir', '../../../../AllData/multi_task/datas/',...
                   'resultDir', '../../../../AllData/multi_task/results/',...
                   'tunedParas', struct(...
                                        'lambdaW'  ,  [1,10,1e+2,1e+3,1e+4],...
                                        'lambdaB' ,   [1,10,1e+2,1e+3,1e+4],...
                                        'lambdaq' ,   [1,10,1e+2,1e+3,1e+4],...
                                        'rank'    ,  [3,10]...
                                        )...
                   )...
 );

options = struct(...
                 'maxIter', 100,...
                 'ftol',    1e-4,... 
                 'bFlag',   0, ...    % 0  this flag tests whether the gradient step only changes a little
                 'tFlag',   3, ...    % 3  the termination criteria
                 'beta',    0.75,  ...   % inertial step size.
                 'alg_version', 5, ... % choose algorithm version [2,3,4,5] 
                 'lip_const', 100 ... % 
);